# Generated by Django 4.1 on 2023-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('acc_no', models.IntegerField(max_length=10)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
