# Generated by Django 4.1 on 2023-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcustomers',
            name='acc_no',
            field=models.IntegerField(),
        ),
    ]
