# Generated by Django 4.1 on 2023-03-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transactionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
