# Generated by Django 4.1 on 2023-03-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='customerid',
            new_name='customer_id',
        ),
    ]
